apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-postgres-app-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/AssNiang/argocd-django-postgres-app-config.git
    targetRevision: HEAD
    path: django-postgres-app
  destination: 
    server: https://kubernetes.default.svc
    namespace: django-postgres-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true