apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
  labels:
    app: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: django-app
  template:
    metadata:
      labels:
        name: django-app
    spec:
      containers:
        - name: django-app
          image: sas792/devops-django:4
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "postgres"
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: database_url


---
# START Service
apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  labels:
    app: django-app
spec:
  selector:
    name: django-app
  ports:
    - port: 8000 #port that the service exposes
      targetPort: 8000 #port that the app is receiving requests from via the pod

# END SERVICE